# Redirect all non-API routes to the SPA entry point
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Proxy API requests to the backend server
[[redirects]]
  from = "/api/*"
  to = "https://m-shop-server-dd28.onrender.com/:splat"
  status = 200
  force = true